name: three-phase-flow
channels:
  - defaults
dependencies:
  - numpy
  - matplotlib
  - opencv
  - scipy
  - pandas
  - pip
  - pip:
    - corner
    - emcee
    - tables
    - googleapiclient
    - google_auth_oauthlib
    - google
    - pickle
