name: three-phase-flow
channels:
  - defaults
dependencies:
  - numpy
  - matplotlib
  - opencv
  - scipy
  - pandas
  - pip
  - os
  - pickle
  - io
  - googleapiclient
  - google_auth_oauthlib
  - google
  - pip:
    - corner
    - emcee
    - tables
