name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _ipyw_jlab_nb_ext_conf=0.1.0
  - alabaster=0.7.10
  - anaconda-client=1.7.2
  - anaconda-navigator=1.9.7
  - anaconda-project=0.8.2
  - asn1crypto=0.24.0
  - astroid=1.6.1
  - astropy=2.0.3
  - attrs=17.4.0
  - babel=2.5.3
  - backports=1.0
  - backports.shutil_get_terminal_size=1.0.0
  - beautifulsoup4=4.6.0
  - bitarray=0.8.1
  - bkcharts=0.2
  - blas=1.0
  - blaze=0.11.3
  - bleach=2.1.2
  - bokeh=0.12.13
  - boto=2.48.0
  - bottleneck=1.2.1
  - bzip2=1.0.6
  - ca-certificates=2019.1.23
  - certifi=2019.3.9
  - cffi=1.11.4
  - chardet=3.0.4
  - click=6.7
  - cloudpickle=0.5.2
  - clyent=1.2.2
  - colorama=0.3.9
  - comtypes=1.1.4
  - conda=4.6.14
  - conda-build=3.4.1
  - conda-env=2.6.0
  - conda-verify=2.0.0
  - console_shortcut=0.1.1
  - contextlib2=0.5.5
  - cryptography=2.6.1
  - curl=7.64.1
  - cycler=0.10.0
  - cython=0.27.3
  - cytoolz=0.9.0
  - dask=0.16.1
  - dask-core=0.16.1
  - datashape=0.5.4
  - decorator=4.2.1
  - distributed=1.20.2
  - docutils=0.14
  - entrypoints=0.2.3
  - et_xmlfile=1.0.1
  - fastcache=1.0.2
  - ffmpeg=2.7.0
  - filelock=2.0.13
  - flask=0.12.2
  - flask-cors=3.0.3
  - freetype=2.8
  - get_terminal_size=1.0.0
  - gevent=1.2.2
  - glob2=0.6
  - greenlet=0.4.12
  - h5py=2.7.1
  - hdf5=1.10.1
  - heapdict=1.0.0
  - html5lib=1.0.1
  - icc_rt=2017.0.4
  - icu=58.2
  - idna=2.6
  - imageio=2.2.0
  - imagesize=0.7.1
  - intel-openmp=2018.0.0
  - ipykernel=4.8.0
  - ipython=6.2.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.1.1
  - isort=4.2.15
  - itsdangerous=0.24
  - jdcal=1.3
  - jedi=0.11.1
  - jinja2=2.10
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.2
  - jupyter_console=5.2.0
  - jupyter_core=4.4.0
  - jupyterlab=0.31.4
  - jupyterlab_launcher=0.10.2
  - krb5=1.16.1
  - lazy-object-proxy=1.3.1
  - libcurl=7.64.1
  - libiconv=1.15
  - libopencv=3.4.2
  - libpng=1.6.37
  - libssh2=1.8.2
  - libtiff=4.0.9
  - libxml2=2.9.7
  - libxslt=1.1.32
  - llvmlite=0.21.0
  - locket=0.2.0
  - lxml=4.1.1
  - lzo=2.10
  - markupsafe=1.0
  - matplotlib=2.1.2
  - mccabe=0.6.1
  - menuinst=1.4.11
  - mistune=0.8.3
  - mkl=2018.0.1
  - mkl-service=1.1.2
  - mpi4py=2.0.0
  - mpmath=1.0.0
  - msgpack-python=0.5.1
  - multipledispatch=0.4.9
  - navigator-updater=0.1.0
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - networkx=2.1
  - nltk=3.2.5
  - nose=1.3.7
  - notebook=5.4.0
  - numba=0.36.2
  - numexpr=2.6.4
  - numpy=1.14.2
  - numpydoc=0.7.0
  - odo=0.5.1
  - olefile=0.45.1
  - openpyxl=2.4.10
  - openssl=1.1.1b
  - packaging=16.8
  - pandas=0.22.0
  - pandoc=1.19.2.1
  - pandocfilters=1.4.2
  - parso=0.1.1
  - partd=0.3.8
  - path.py=10.5
  - pathlib2=2.3.0
  - patsy=0.5.0
  - pep8=1.7.1
  - pickleshare=0.7.4
  - pillow=5.0.0
  - pip=9.0.1
  - pkginfo=1.4.1
  - pluggy=0.6.0
  - ply=3.10
  - prompt_toolkit=1.0.15
  - psutil=5.4.3
  - py=1.5.2
  - py-opencv=3.4.2
  - pycodestyle=2.3.1
  - pycosat=0.6.3
  - pycparser=2.18
  - pycrypto=2.6.1
  - pycurl=7.43.0.2
  - pyflakes=1.6.0
  - pygments=2.2.0
  - pylint=1.8.2
  - pyodbc=4.0.22
  - pyopenssl=17.5.0
  - pyparsing=2.2.0
  - pyqt=5.9.2
  - pysocks=1.6.7
  - pytables=3.4.2
  - pytest=3.3.2
  - python=3.6.4
  - python-dateutil=2.6.1
  - pytz=2017.3
  - pywavelets=0.5.2
  - pywin32=222
  - pywinpty=0.5
  - pyyaml=3.12
  - pyzmq=16.0.3
  - qt=5.9.7
  - qtawesome=0.4.4
  - qtconsole=4.3.1
  - qtpy=1.5.2
  - requests=2.18.4
  - rope=0.10.7
  - ruamel_yaml=0.15.35
  - scikit-image=0.13.1
  - scikit-learn=0.19.1
  - scipy=1.0.0
  - seaborn=0.8.1
  - send2trash=1.4.2
  - setuptools=38.4.0
  - simplegeneric=0.8.1
  - singledispatch=3.4.0.3
  - sip=4.19.8
  - six=1.11.0
  - snowballstemmer=1.2.1
  - sortedcollections=0.5.3
  - sortedcontainers=1.5.9
  - sphinx=1.6.6
  - sphinxcontrib=1.0
  - sphinxcontrib-websupport=1.0.1
  - spyder=3.2.6
  - sqlalchemy=1.2.1
  - sqlite=3.28.0
  - statsmodels=0.8.0
  - sympy=1.1.1
  - tblib=1.3.2
  - terminado=0.8.1
  - testpath=0.3.1
  - tk=8.6.8
  - toolz=0.9.0
  - tornado=4.5.3
  - traitlets=4.3.2
  - typing=3.6.2
  - unicodecsv=0.14.1
  - urllib3=1.22
  - vc=14.1
  - vs2015_runtime=14.15.26706
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.14.1
  - wheel=0.30.0
  - widgetsnbextension=3.1.0
  - win_inet_pton=1.0.1
  - win_unicode_console=0.5
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.10.11
  - xlrd=1.1.0
  - xlsxwriter=1.0.2
  - xlwings=0.11.5
  - xlwt=1.3.0
  - yaml=0.1.7
  - zict=0.1.3
  - zlib=1.2.11
  - pip:
    - corner==2.0.1
    - emcee==2.2.1

