name: three-phase-flow
channels:
  - defaults
dependencies:
  - numpy
  - matplotlib
  - pandas
  - pip
  - pip:
    - corner
    - emcee
    - tables
    - google-api-python-client
    - google-auth-oauthlib
